version: '3'
services:
  postgres:
    image: postgres:18
    container_name: postgres-db
    environment:
      POSTGRES_DB: paytestdb
      POSTGRES_USER: paytestuser
      POSTGRES_PASSWORD: 123456789
    volumes:
      - postgres-data:/var/lib/postgresql/18/data
      - ./Postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paytestuser -d paytestdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    environment:
      DB_HOST: postgres
      DB_NAME: paytestdb
      DB_USER: paytestuser
      DB_PASSWORD: 123456789
      POOL_MODE: transaction     
      MAX_CLIENT_CONN: 10000      
      DEFAULT_POOL_SIZE: 40     
      MAX_DB_CONNECTIONS: 100    
    depends_on:
      - postgres
  paydealerservice:
    build: ./paydealerservice
    container_name: paydealerservice
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  payconsumerservice:
    build: ./payconsumerservice
    container_name: payconsumerservice
    depends_on:
      - postgres
      - paydealerservice
    environment:
      BOUNCER_URL: r2dbc:postgresql://pgbouncer:6432/paytestdb
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paytestdb
      SPRING_DATASOURCE_USERNAME: paytestuser
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/paytestdb
      SPRING_R2DBC_USERNAME: paytestuser
      SPRING_R2DBC_PASSWORD: 123456789
      DEALER_URL: http://paydealerservice:8080
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  payconsumerfront:
    build: ./payconsumerfront
    container_name: payconsumerfront
    ports:
      - "80:80" 
    depends_on:
      - payconsumerservice
    environment:
      BACKEND_HOST: payconsumerservice
      BACKEND_PORT: 8080
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    depends_on:
      - payconsumerservice
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./Grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
volumes:
  postgres-data: